#注：修改后重启生效，请严格按照yaml语法进行修改，否则会出现意料之外的错误
#key值设置为要触发的词
bs:
  url:
    - http://api.starrobotwl.com/api/baisi.php
    - http://api.caonm.net/api/bhs/b.php #url可使用数组设置多个触发时随机抽取或用数字指定

  type: image
  #根据接口指定类型类型包括 image text json 如不写则默认为image
  # image指接口直接返回图片
  # text指接口返回链接
  # json指接口返回json字符串 ,返回json需指定path请参考以下json示例

#也可以以正则设置触发词
hs|黑丝:
  url:
    - http://api.caonm.net/api/bhs/h.php
    - http://api.starrobotwl.com/api/heisi.php

#返回json示例
pixiv:
  url: https://sex.nyan.xyz/api/v2/
  type: json
  path: data[0].url #接口返回链接在 "data数组" 里面用 "[0]" 来指定数组的第几个值后再 ".url" 即可，最后必须指向图片链接

bm:
  url: http://iw233.cn/api.php?sort=yin #在url字段后面写链接，仅限直接返回图片的api

sy: https://iw233.cn/api.php?sort=cat #或者直接写链接效果同上

jk:
  url:
    - http://api.starrobotwl.com/api/jk.php
    - http://www.ggapi.cn/api/jkzf

mt:
  - https://api.sdgou.cc/api/meitui/
  - https://ovooa.com/API/meizi/api.php?type=image #一个指令设置多个API

ks: http://api.wqwlkj.cn/wqwlapi/ks_xjj.php?type=image

fj: http://api.starrobotwl.com/api/fuji.php

ecy:
  - https://iw233.cn/api.php?sort=top
  - https://iw233.cn/api.php?sort=mp
  - http://api.wqwlkj.cn/wqwlapi/ks_2cy.php?type=image

cos: http://api.starrobotwl.com/api/yscos.php

hso: http://www.ggapi.cn/api/girls

xjj:
  - https://api.btstu.cn/sjbz/api.php
  - https://ovooa.com/API/meinv/api.php?type=image
  - http://api.sakura.gold/ksxjjtp

mjx:
  - https://api.sdgou.cc/api/tao/
  - https://api.vvhan.com/api/tao
  - https://api.dzzui.com/api/imgtaobao
